package com.enwerevincent.invest.enums;

public enum NotificationType {
    REGISTER_NOTIFICATION,
    LOGIN_NOTIFICATION,
    DEPOSIT_NOTIFICATION,
    WITHDRAWAL_NOTIFICATION,
    INVEST_NOTIFICATION,
    END_OF_INVESTMENT_NOTIFICATION,
}
